[project]
name = "ms-database-connector"
version = "0.1.0"
description = "Fluid4.0 Microservice Database Connector"
authors = [
    {name = "Celina Adelhardt", email = "celina.adelhardt@em.ag"}
]
requires-python = ">=3.11"
license = { file = "LICENSE" }
readme = "README.md"
keywords = ["influxdb", "AAS", "python", "microservice", "fluid4.0"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"

# Missing library stubs or py.typed marker files are ignored to avoid mypy errors.
[[tool.mypy.overrides]]
module = ["influxdb.*", "aas_http_client", "aas_http_client.*"]
ignore_missing_imports = true

[tool.poetry.dependencies]
pydantic = "^2.13.4"
requests = "^2.33.1"
influxdb = "^5.3.2"
fastapi = "^0.138.0"
python = ">=3.11,<4.0"
influxdb-client = ">=1.35.0"
uvicorn = "^0.49.0"
aas-http-client = "^1.0.11"
aas-standard-parser = "^0.6.4"
basyx-python-sdk = "^2.0.1"
fastapi-health = "^0.4.0"
pydantic-settings = "^2.14.1"
pydantic-core = "^2.47.0"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "pytest-mock (>=3.14.1,<4.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]
