var searchData=
[
  ['raw_5fmapping_5fwith_5funfilled_0',['raw_mapping_with_unfilled',['../namespacetest__db__mapping__validation.html#ae7766cf68636e7cc95b622104d6a95ce',1,'test_db_mapping_validation']]],
  ['rawdbmapping_1',['RawDbMapping',['../classms__database__connector_1_1config_1_1db__mapping_1_1RawDbMapping.html',1,'ms_database_connector::config::db_mapping']]],
  ['rawmeasurementmapping_2',['RawMeasurementMapping',['../classms__database__connector_1_1config_1_1db__mapping_1_1RawMeasurementMapping.html',1,'ms_database_connector::config::db_mapping']]],
  ['reachability_20tt_3',['6) &lt;tt&gt;InfluxDB connection failed. Set INFLUXDB_V2_TOKEN and ensure server reachability.&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md24',1,'']]],
  ['read_5flog_5ffile_5fas_5flist_4',['read_log_file_as_list',['../namespacems__database__connector_1_1utils_1_1logging__handler.html#a5b3db28d6de2da898049f5fca05eb0da',1,'ms_database_connector::utils::logging_handler']]],
  ['readme_2emd_5',['README.md',['../README_8md.html',1,'']]],
  ['ready_20to_20go_20configuration_20file_6',['Option 1: Use a ready-to-go configuration file',['../md_docs_2process.html#autotoc_md58',1,'']]],
  ['recommended_20tt_20env_20tt_20file_7',['Recommended &lt;tt&gt;.env&lt;/tt&gt; file',['../md_docs_2configuration.html#autotoc_md6',1,'']]],
  ['reconnect_5finflux_5fclient_8',['reconnect_influx_client',['../namespacems__database__connector_1_1dependencies.html#ac1cfb046bdd73c068c586c737ff52ccb',1,'ms_database_connector::dependencies']]],
  ['red_9',['red',['../classms__database__connector_1_1utils_1_1logging__handler_1_1ColorCodes.html#aea9a8678e1020b9a3b7801e61c81307b',1,'ms_database_connector::utils::logging_handler::ColorCodes']]],
  ['reference_10',['Field reference',['../md_docs_2configuration.html#autotoc_md14',1,'']]],
  ['reference_20mapping_20phase_11',['2. Reference Mapping Phase',['../md_docs_2mapping.html#autotoc_md36',1,'']]],
  ['registry_12',['Option 2: Configure DBC for usage of Registry',['../md_docs_2process.html#autotoc_md62',1,'']]],
  ['registry_20configuration_13',['registry configuration',['../md_docs_2configuration.html#autotoc_md9',1,'AAS Registry Configuration'],['../md_docs_2configuration.html#autotoc_md10',1,'Submodel Registry Configuration']]],
  ['registry_20configuration_20files_20found_20tt_20or_20tt_20no_20submodel_20registry_20configuration_20files_20found_20tt_14',['4) &lt;tt&gt;No AAS registry configuration files found...&lt;/tt&gt; or &lt;tt&gt;No Submodel registry configuration files found...&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md22',1,'']]],
  ['registry_20connection_20file_20tt_20tt_20invalid_20submodel_20registry_20connection_20file_20tt_15',['5) &lt;tt&gt;Invalid AAS registry connection file.&lt;/tt&gt; / &lt;tt&gt;Invalid Submodel registry connection file.&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md23',1,'']]],
  ['release_20bundle_16',['GitHub Release Bundle',['../index.html#autotoc_md72',1,'']]],
  ['reload_5fdb_5fmapping_5ffrom_5ffile_17',['reload_db_mapping_from_file',['../classms__database__connector_1_1utils_1_1mapping__handler_1_1DbMappingHandler.html#a22876618d5aefe38a91ec93168d0a372',1,'ms_database_connector::utils::mapping_handler::DbMappingHandler']]],
  ['repo_5fserver_5fconfigurations_18',['repo_server_configurations',['../classmock__server__config__loader_1_1MockServerConfigLoader.html#a9fee068bb9012831ee807ee8f3ce3022',1,'mock_server_config_loader.MockServerConfigLoader.repo_server_configurations'],['../classms__database__connector_1_1utils_1_1configuration__handling_1_1ServerConfigurationsHandler.html#a8a51ec8800483370aa96dccd41bdec09',1,'ms_database_connector.utils.configuration_handling.ServerConfigurationsHandler.repo_server_configurations'],['../classms__database__connector_1_1config_1_1server__config__loader_1_1ServerConfigLoader.html#ac9a77bbf632499c42762e67949daa736',1,'ms_database_connector.config.server_config_loader.ServerConfigLoader.repo_server_configurations']]],
  ['repository_20server_20configuration_19',['Repository Server Configuration',['../md_docs_2configuration.html#autotoc_md11',1,'']]],
  ['required_20folder_20structure_20',['Required Folder Structure',['../md_docs_2configuration.html#autotoc_md4',1,'']]],
  ['reset_21',['reset',['../classms__database__connector_1_1utils_1_1logging__handler_1_1ColorCodes.html#a5f108370429fe8523721d2b88a5b5dc8',1,'ms_database_connector::utils::logging_handler::ColorCodes']]],
  ['resources_22',['Resources',['../index.html#autotoc_md73',1,'']]],
  ['retrieval_20failures_23',['Retrieval Failures',['../md_docs_2mapping.html#autotoc_md49',1,'']]],
  ['retrieval_20phase_24',['4. Value Retrieval Phase',['../md_docs_2mapping.html#autotoc_md38',1,'']]],
  ['router_25',['router',['../namespacems__database__connector_1_1routers_1_1endpoints.html#ac9cc4126a9addfc69b0a0e7f2a918446',1,'ms_database_connector::routers::endpoints']]],
  ['rsquo_20not_20found_26',['rsquo not found',['../md_docs_2configuration.html#autotoc_md21',1,'3) &amp;lsquo;Configuration base path &apos;configuration&amp;rsquo; not found.`'],['../md_docs_2configuration.html#autotoc_md26',1,'8) &amp;lsquo;...descriptor with ID &amp;rsquo;...&apos; not found...`']]],
  ['rsquo_20service_5fconfig_20json_20not_20found_20or_20inaccessible_27',['2) &amp;lsquo;Configuration file &amp;rsquo;.../service_config.json&apos; not found or inaccessible.`',['../md_docs_2configuration.html#autotoc_md20',1,'']]],
  ['run_28',['Database Connector API (development run)',['../index.html#autotoc_md71',1,'']]]
];
