var searchData=
[
  ['failed_20set_20influxdb_5fv2_5ftoken_20and_20ensure_20server_20reachability_20tt_0',['6) &lt;tt&gt;InfluxDB connection failed. Set INFLUXDB_V2_TOKEN and ensure server reachability.&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md24',1,'']]],
  ['failures_1',['failures',['../md_docs_2mapping.html#autotoc_md48',1,'Access Validation Failures'],['../md_docs_2mapping.html#autotoc_md50',1,'Assignment Failures'],['../md_docs_2mapping.html#autotoc_md49',1,'Retrieval Failures']]],
  ['features_2',['Features',['../index.html#autotoc_md65',1,'']]],
  ['field_3',['FIELD',['../classms__database__connector_1_1config_1_1db__mapping_1_1MappingTargetType.html#a707d136666510b200cf355f320d87bba',1,'ms_database_connector::config::db_mapping::MappingTargetType']]],
  ['field_20reference_4',['Field reference',['../md_docs_2configuration.html#autotoc_md14',1,'']]],
  ['fields_5',['fields',['../classms__database__connector_1_1models_1_1influx__data_1_1InfluxDataPoint.html#a31380e17f99b90e7843244c150e96afe',1,'ms_database_connector::models::influx_data::InfluxDataPoint']]],
  ['file_6',['file',['../md_docs_2configuration.html#autotoc_md5',1,'Environment Variables (using .env file)'],['../md_docs_2process.html#autotoc_md58',1,'Option 1: Use a ready-to-go configuration file'],['../md_docs_2configuration.html#autotoc_md6',1,'Recommended &lt;tt&gt;.env&lt;/tt&gt; file']]],
  ['file_20provided_20tt_7',['1) &lt;tt&gt;No configuration file provided.&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md19',1,'']]],
  ['file_20rsquo_20service_5fconfig_20json_20not_20found_20or_20inaccessible_8',['2) &amp;lsquo;Configuration file &amp;rsquo;.../service_config.json&apos; not found or inaccessible.`',['../md_docs_2configuration.html#autotoc_md20',1,'']]],
  ['file_20tt_9',['7) &lt;tt&gt;No Asset Administration Shell ID provided in configuration file.&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md25',1,'']]],
  ['file_20tt_20tt_20invalid_20submodel_20registry_20connection_20file_20tt_10',['5) &lt;tt&gt;Invalid AAS registry connection file.&lt;/tt&gt; / &lt;tt&gt;Invalid Submodel registry connection file.&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md23',1,'']]],
  ['files_20found_20tt_20or_20tt_20no_20submodel_20registry_20configuration_20files_20found_20tt_11',['4) &lt;tt&gt;No AAS registry configuration files found...&lt;/tt&gt; or &lt;tt&gt;No Submodel registry configuration files found...&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md22',1,'']]],
  ['flag_12',['flag',['../namespacems__database__connector_1_1____main____.html#a58b65b476af7edefd39e9d2bf0438d40',1,'ms_database_connector::__main__']]],
  ['flow_13',['Process Flow',['../md_docs_2mapping.html#autotoc_md31',1,'']]],
  ['flow_20example_14',['Data Flow Example',['../md_docs_2mapping.html#autotoc_md43',1,'']]],
  ['folder_20structure_15',['Required Folder Structure',['../md_docs_2configuration.html#autotoc_md4',1,'']]],
  ['for_20data_20visualization_20in_20influxdb_16',['Tips and Tricks for Data Visualization in InfluxDB',['../md_docs_2visualization.html',1,'']]],
  ['for_20database_20connector_20demo_20workflow_17',['Setup for Database Connector Demo Workflow',['../md_docs_2demo.html',1,'']]],
  ['for_20direct_20integration_20with_20ms_20data_20mapping_20processor_18',['Option 1: Configure DBC for direct integration with ms-data-mapping-processor',['../md_docs_2process.html#autotoc_md61',1,'']]],
  ['for_20example_20invalid_20target_20type_20or_20multiple_20timestamps_19',['9) Mapping validation errors (for example invalid target type or multiple timestamps)',['../md_docs_2configuration.html#autotoc_md27',1,'']]],
  ['for_20usage_20of_20registry_20',['Option 2: Configure DBC for usage of Registry',['../md_docs_2process.html#autotoc_md62',1,'']]],
  ['format_21',['format',['../md_docs_2mapping.html#autotoc_md41',1,'DB Mapping Format'],['../classms__database__connector_1_1utils_1_1logging__handler_1_1CustomConsoleFormatter.html#a010eacadb11d8632ad21d35849f047bc',1,'ms_database_connector.utils.logging_handler.CustomConsoleFormatter.format(self, record)']]],
  ['formats_22',['FORMATS',['../classms__database__connector_1_1utils_1_1logging__handler_1_1CustomConsoleFormatter.html#a12324d5722d9cc1aae2cc92ff59f207e',1,'ms_database_connector::utils::logging_handler::CustomConsoleFormatter']]],
  ['found_23',['found',['../md_docs_2configuration.html#autotoc_md21',1,'3) &amp;lsquo;Configuration base path &apos;configuration&amp;rsquo; not found.`'],['../md_docs_2configuration.html#autotoc_md26',1,'8) &amp;lsquo;...descriptor with ID &amp;rsquo;...&apos; not found...`']]],
  ['found_20or_20inaccessible_24',['2) &amp;lsquo;Configuration file &amp;rsquo;.../service_config.json&apos; not found or inaccessible.`',['../md_docs_2configuration.html#autotoc_md20',1,'']]],
  ['found_20tt_20or_20tt_20no_20submodel_20registry_20configuration_20files_20found_20tt_25',['4) &lt;tt&gt;No AAS registry configuration files found...&lt;/tt&gt; or &lt;tt&gt;No Submodel registry configuration files found...&lt;/tt&gt;',['../md_docs_2configuration.html#autotoc_md22',1,'']]],
  ['from_20submodelelements_20to_20influx_20objects_26',['Mapping Process: From SubmodelElements to Influx Objects',['../md_docs_2mapping.html',1,'']]],
  ['future_20enhancements_27',['Future Enhancements',['../md_docs_2mapping.html#autotoc_md56',1,'']]]
];
