---
services:
  # influx_database_v1:
  #   image: influxdb:1.11.8
  #   container_name: ms-dbc-influx-v1
  #   volumes:
  #     - influxdb_v1_data:/var/lib/influxdb
  #   restart: always
  #   environment:
  #     INFLUXDB_DB: submodel-db
  #     INFLUXDB_ADMIN_USER: admin
  #     INFLUXDB_ADMIN_PASSWORD: fluid40secure!
  #     INFLUXDB_USER: fluid40
  #     INFLUXDB_USER_PASSWORD: wbEx!S!#4OHcN!5X
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s

  influx_database_v2:
    image: influxdb:2.7
    container_name: ms-dbc-influx-v2
    ports:
      - "8031:8086"
    volumes:
      - influxdb_v2_data:/var/lib/influxdb2
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: fluid40secure!
      DOCKER_INFLUXDB_INIT_ORG: fluid40-org
      DOCKER_INFLUXDB_INIT_BUCKET: fluid40-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: wbEx!S!#4OHcN!5X
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  dev_container:
    build: .
    container_name: ms-dbc-dev-container
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      # influx_database_v1:
      # condition: service_healthy
      influx_database_v2:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "keycloak.basyx.localhost:host-gateway"
      - "aasreg.basyx.localhost:host-gateway"
      - "smreg.basyx.localhost:host-gateway"
      - "aasenv.basyx.localhost:host-gateway"
    environment:
      - DBC_CONFIGURATION_FILE=/workspaces/ms-database-connector/configuration/service_config.json
      - INFLUXDB_V2_TOKEN=$INFLUXDB_V2_TOKEN
      - DBC_AAS_CLIENT_SECRET=$DBC_AAS_CLIENT_SECRET

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:$BASYX_VERSION
    container_name: ms-dbc-aas-registry
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: aasreg.basyx.localhost
      VIRTUAL_PORT: "8080"
      SERVER_SERVLET_CONTEXT_PATH: /
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: >-
        http://keycloak.basyx.localhost/realms/BaSyx
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: >-
        file:/workspace/config/rbac_rules.json
    volumes:
      - ./basyx/rules/aas_registry_rbac_rules.json:/workspace/config/rbac_rules.json
    restart: always
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    ports:
      - "8076:8080"
    networks:
      - bridge

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:$BASYX_VERSION
    container_name: ms-dbc-sm-registry
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: smreg.basyx.localhost
      VIRTUAL_PORT: "8080"
      SERVER_SERVLET_CONTEXT_PATH: /
      BASYX_CORS_ALLOWED_ORIGINS: "*"
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: >-
        http://keycloak.basyx.localhost/realms/BaSyx
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: >-
        file:/workspace/config/rbac_rules.json
    volumes:
      - ./basyx/rules/sm_registry_rbac_rules.json:/workspace/config/rbac_rules.json
    restart: always
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    ports:
      - "8077:8080"
    networks:
      - bridge

  aas-discovery:
    image: eclipsebasyx/aas-discovery:$BASYX_VERSION
    container_name: ms-dbc-aas-discovery
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: discovery.basyx.localhost
      VIRTUAL_PORT: "8081"
    volumes:
      - ./basyx/aas-discovery.properties:/application/application.properties
      - ./basyx/rules/aas_discovery_rbac_rules.json:/application/rbac_rules.json
    ports:
      - "8084:8081"
    restart: always
    depends_on:
      keycloak-healthcheck:
        condition: service_completed_successfully
    networks:
      - bridge

  aas-env:
    image: eclipsebasyx/aas-environment:$BASYX_VERSION
    container_name: ms-dbc-aas-server
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    ports:
      - "8081:8081"
    environment:
      VIRTUAL_HOST: aasenv.basyx.localhost
      VIRTUAL_PORT: "8081"
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
      - ./basyx/rules/aas_env_rbac_rules.json:/application/rbac_rules.json
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
    networks:
      - bridge

  aas-web-ui:
    image: eclipsebasyx/aas-gui:$AAS_WEBUI_VERSION
    container_name: ms-dbc-aas-web-ui
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    ports:
      - "8078:3000"
    environment:
      VIRTUAL_HOST: aasgui.basyx.localhost
      VIRTUAL_PORT: "3000"
      AAS_REGISTRY_PATH: http://aasreg.basyx.localhost/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://smreg.basyx.localhost/submodel-descriptors
      AAS_REPO_PATH: http://aasenv.basyx.localhost/shells
      SUBMODEL_REPO_PATH: http://aasenv.basyx.localhost/submodels
      CD_REPO_PATH: http://aasenv.basyx.localhost/concept-descriptions
      AAS_DISCOVERY_PATH: http://discovery.basyx.localhost/lookup/shells
      PRIMARY_COLOR: "#00A0C7"
      LOGO_LIGHT_PATH: fluid40_light.png
      LOGO_DARK_PATH: fluid40_dark.png
      KEYCLOAK_URL: http://keycloak.basyx.localhost
      KEYCLOAK_REALM: BaSyx
      KEYCLOAK_CLIENT_ID: basyx-web-ui
    volumes:
      - ./logo:/usr/src/app/dist/Logo
    depends_on:
      aas-env:
        condition: service_healthy
    networks:
      - bridge

  # nginx reverse proxy to support dns lookup
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.0-alpine
    container_name: ms-dbc-nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: aasgui.basyx.localhost
    networks:
      - bridge

  keycloak:
    image: keycloak/keycloak:24.0.4
    container_name: ms-dbc-keycloak
    environment:
      VIRTUAL_HOST: keycloak.basyx.localhost
      VIRTUAL_PORT: "8080"
      KC_HOSTNAME: keycloak.basyx.localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak-admin
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HEALTH_ENABLED: "true"
      KC_IMPORT: /opt/keycloak/data/import/
    command: ["start-dev", "--import-realm"]
    ports:
      - 9095:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      - bridge

  keycloak-healthcheck:
    image: curlimages/curl:latest
    container_name: ms-dbc-keycloak-healthcheck
    command: >
      sh -c "
        echo 'Waiting for Keycloak to become ready...';
        until curl -sf http://ms-dbc-keycloak:8080/health/ready; do
          sleep 5;
        done;
        echo 'Keycloak is ready!'"
    depends_on:
      - keycloak
    networks:
      - bridge

networks:
  bridge:

volumes:
  # influxdb_v1_data:
  influxdb_v2_data:
